### PR TITLE
test: update listX tests to account for compile error

### PR DESCRIPTION
**Pull request by danielleadams**
#### Description of changes
Updates tests to reflect errors thrown from here: https://github.com/aws-amplify/amplify-category-api/pull/517

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by marcvberg — APPROVED** [review]
LGTM

**Comment by danielleadams** [comment]
@marcvberg I had to rebase, so it needs another review

**Review by marcvberg — DISMISSED** [review]

**Comment by alharris-at** [comment]
I'm slightly confused, why not just make the fix as part of that PR instead of separately?

**Comment by danielleadams** [comment]
@alharris-at I originally did this because I didn't catch the failures until I ran e2e separately and I didn't want to overturn the reviews, but I had to rebase both, so I the reviews were dismissed. I can cherry-pick this into https://github.com/aws-amplify/amplify-category-api/pull/517.

**Comment by danielleadams** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-category-api/pull/517

**Pull request closed without merging**
