### PR TITLE
Fix incorrect resolvers leading to Unauthorized when using groupsField with index

### LINKED ISSUE #468: Secondary @index query data not accessible due to not authorize error with graphql gransformerv2
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16

### Amplify CLI Version

7.6.7

### What operating system are you using?

Ubuntu WSL

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Upgrade to graphql transformer v2

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

After upgrading to the new graphql transformer my queries that use secondary indexes can no longer be used by our users as they appear to now be "unauthorized" via dynamic group authorisation.
When executing `farmsByCustomer` I now get
```
  "errors": [
    {
      "path": [
        "farmsByCustomer"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access farmsByCustomer on type ModelFarmConnection"
    }
  ]
  ```

This seems to not be the case for static group authorisation (role_superadmin still can access the data fine).

All queries were executed via the appsync console to exclude our client code from having any impact on the issue.

### Expected behavior

Users can still access data via custom indexes or instructions on how to allow access to the custom index.

### Reproduction steps

1. old model with expected behaviour (data accessible via gsi)
2. run transform
3. data no longer accessible

### GraphQL schema(s)

<details>

```graphql
type Farm
  @model
  @auth(
    rules: [
      {
        allow: groups
        groups: ["role_superadmin"]
        operations: [create, update, delete, read]
      },
      { allow: groups, groupsField: "customerName", operations: [read] },
      { allow: groups, groups: ["bpe"], operations: [read] },
      { allow: private, provider: iam, operations: [create, read, update] }
    ]
  ) {
  name: String! @primaryKey
  location: String! # europe_austria_vienna -> we can query by BEGINS_WITH to efficiently filter if we put this in a sort key
  type: FarmType
  latitude: Float
  longitude: Float
  weather: Weather
  weatherForecasts: [Weather]
  weatherWarnings: [WeatherWarning]
  customerName: String!
    @index(
      name: "byCustomerName"
      queryField: "farmsByCustomer"
      sortKeyFields: ["location"]
    )
  status: FarmStatus
  customer: Customer @belongsTo(fields: ["customerName"])
  units: [Unit]
    @hasMany(
      indexName: "byCustomerAndFarmName"
      fields: ["customerName", "name"]
    )
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

_No response_

### LINKED ISSUE #857: GraphQL query generated by @index directive fails with Unauthorized error when field is used as @auth groupsField
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

_No response_

### If applicable, what version of Node.js are you using?

_No response_

### Amplify CLI Version

7.6.15

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, api

### Amplify Commands

push

### Describe the bug

We migrated our GraphQL model from v1 to v2 as per the migration instructions. A new error seems to have been introduced that gives `Unauthorized` errors when running an index query on a field that is used as a `groupsField`. Schema:

```graphql
type Application @model @searchable @auth(rules: [{allow: groups, groupsField: "projectId"}, {allow: private, operations: [create]}]) {
  id: ID!
  projectId: ID! @index(name: "byProjectId", queryField: "applicationsByProjectId")
  applicationName: String! @index(name: "byApplicationName", queryField: "applicationByName")
  ...
}
```

The generated query `applicationByName` works fine and returns only the items that the user is authorized to see via their group membership, however, the `applicationsByProjectId` query fails and gives the error:
```
Not Authorized to access applicationsByProjectId on type ModelApplicationConnection
```
The only difference between these two queries is that the `projectId` field is used as a `groupsField` in the auth rule, so we assume this is causing the issue.

### Expected behavior

As with before migration to the Transformer V2, both the applicationsByProjectId and applicationByName should return data and not return an unauthorized error.

### Reproduction steps

1. Create a model with an @auth rule that contains a `groupsField`
2. Add fields to the model with @index directives containing a queryField parameter, including on the field that is the `groupsField`
3. Run the GraphQL query for the groupsField index, it will return unauthorized. The other queries will succeed.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Application @model @searchable @auth(rules: [{allow: groups, groupsField: "projectId"}, {allow: private, operations: [create]}]) {
  id: ID!
  projectId: ID! @index(name: "byProjectId", queryField: "applicationsByProjectId")
  applicationName: String! @index(name: "byApplicationName", queryField: "applicationByName")
  applicationType: String
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Booligoosh**
#### Description of changes

$parentClaim is an array, so $ownerClaimsList0.add($parentClaim) will make a nested array, hence $ownerClaimsList0.contains($ctx.args.parent) will always return false.

This change replaces .add with .addAll, which adds the *contents* of $parentClaim to the $ownerClaimsList0 array, hence $ownerClaimsList0.contains($ctx.args.parent) will match the groups as expected.

#### Issue #, if available

Resolves #857
Resolves #468

#### Description of how you validated changes

Patched CLI and pushed up the new resolvers. Tested a user who was in a group that was allowed access based on the groupsField, and it allowed access. Tested a user who wasn't in a group that was allowed access based on the groupsField, and it denied access.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rideddy84** [comment]
I hope it's resolved soon. 😰

**Comment by rideddy84** [comment]
I'm using Amplify on production. This issue is so critical.

**Comment by rideddy84** [comment]
Please let me have a happy Christmas. 🎄

**Comment by Booligoosh** [comment]
Hi Amplify team @sundersc @sobolk, wondering if there is any update on this? It's been 5 months and this issue still exists, the fix is fairly simple. For now we have been having to use a custom built version of Amplify with this patch applied. Cheers 🙂

**Comment by sundersc** [comment]
Hey @Booligoosh - Sorry about the delay. Appreciate your patience. 

I don't think we can assume that claim is an array in all cases. We should probably do a check similar to the one shown below (taken from create mutation resolver) and convert into an array before calling `addAll`. 

```vtl
    #set( $groupEntity0 = $util.defaultIfNull($ctx.args.input.projectId, null) )
    #set( $groupClaim0 = $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), []) )
    #if( $util.isString($groupClaim0) )
      #if( $util.isList($util.parseJson($groupClaim0)) )
        #set( $groupClaim0 = $util.parseJson($groupClaim0) )
      #else
        #set( $groupClaim0 = [$groupClaim0] )
      #end
    #end
```

**Comment by Booligoosh** [comment]
Hi @sundersc, no worries, thanks for the quick reply. That makes sense, would you like me to add that to the PR? (I would remove the .add & .addAll completely and replace it with that logic)

**Comment by sundersc** [comment]
@Booligoosh - I had to run a bunch of tests so I pulled your changes to my fork and created a new PR.

Closing this in favor of https://github.com/aws-amplify/amplify-category-api/pull/1363.

**Pull request closed without merging**
