### PR TITLE
Adding model rds e2e

### PR DESCRIPTION
**Pull request by marcvberg**
#### Description of changes
Adds an E2E test for RDS which runs mutations through appsync

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [ ] Any CDK or CloudFormation parameter changes are called out explicitly

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by phani-srikar — CHANGES_REQUESTED** [review]
Please update the conflicting file and include a link to successful run of added e2e test.

**Comment by marcvberg** [comment]
Unable to run E2E now because the RDS branch is behind main, even trying to work around it locally is nontrivial. I'll try merging main in to a dummy branch locally tomorrow to validate

**Comment by marcvberg** [comment]
merging main was unsuccessful. Will run E2E normally after the feature branch is updated and I can rebase

**Comment by sundersc** [comment]
Closing this PR as lot of E2E core methods are going to change with the updated CLI workflow and updated logic to move the core SQL logic to a lambda layer.

However there are bits of query testing can be reused in a new PR.

**Pull request closed without merging**
