### PR TITLE
Merge main into RDS feature branch

### PR DESCRIPTION
**Pull request by marcvberg**
#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [ ] Any CDK or CloudFormation parameter changes are called out explicitly

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by phani-srikar — CHANGES_REQUESTED** [review]
Couple of things still need to be updated in the `amplify-graphql-schema-generator` package:
1. Update the version of `@aws-amplify/graphql-transformer-core` to latest `1.2.0`.
2. Update the `amplify-prompts` dependency to `"@aws-amplify/amplify-prompts": "^2.6.6"`.
3. Modify the imports of `amplify-prompts` to use the scoped name.

**Comment by marcvberg** [comment]
@phani-srikar Done

**Comment by phani-srikar** [comment]
There are still some places where we are importing non-scoped `amplify-cli-core` and `amplify-prompts`. I noticed them in these files: [file1](https://github.com/aws-amplify/amplify-category-api/blob/bb6c8c93aa98dd61f3a1cc281deffb5739687acf/packages/amplify-category-api/src/provider-utils/awscloudformation/utils/graphql-schema-utils.ts#L5), [file2](https://github.com/aws-amplify/amplify-category-api/blob/bb6c8c93aa98dd61f3a1cc281deffb5739687acf/packages/amplify-category-api/src/commands/api/generate-schema.ts#L1), [file3](https://github.com/aws-amplify/amplify-category-api/blob/bb6c8c93aa98dd61f3a1cc281deffb5739687acf/packages/amplify-category-api/src/commands/api/import.ts#L2), [file4](https://github.com/aws-amplify/amplify-category-api/blob/bb6c8c93aa98dd61f3a1cc281deffb5739687acf/packages/amplify-category-api/src/commands/api/update-secrets.ts#L2), [file5](https://github.com/aws-amplify/amplify-category-api/blob/bb6c8c93aa98dd61f3a1cc281deffb5739687acf/packages/amplify-category-api/src/provider-utils/awscloudformation/utils/rds-secrets/database-secrets.ts#L7), [file6](https://github.com/aws-amplify/amplify-category-api/blob/bb6c8c93aa98dd61f3a1cc281deffb5739687acf/packages/amplify-category-api/src/provider-utils/awscloudformation/utils/rds-secrets/multi-env-database-secrets.ts#L3), [file7](https://github.com/aws-amplify/amplify-category-api/blob/bb6c8c93aa98dd61f3a1cc281deffb5739687acf/packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/import-appsync-api-walkthrough.ts#L2). These need to be converted to scoped imports.

**Comment by marcvberg** [comment]
Corrected

**Review by phani-srikar — APPROVED** [review]
LGTM!

**Review by alharris-at — APPROVED** [review]

**Review by sundersc — APPROVED** [review]

**Pull request merged**
